// <auto-generated />
using System;
using AssetTrackingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetTrackingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521101629_AddAssetInheritance")]
    partial class AddAssetInheritance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetTrackingSystem.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LocalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePriceUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WarrantyExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Assets", (string)null);

                    b.HasDiscriminator<string>("AssetCategory").HasValue("General");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AssetTrackingSystem.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Sweden",
                            Currency = "SEK",
                            Name = "Sweden Office"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Currency = "USD",
                            Name = "USA Office"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Currency = "EUR",
                            Name = "Germany Office"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Turkey",
                            Currency = "TRY",
                            Name = "Turkey Office"
                        });
                });

            modelBuilder.Entity("AssetTrackingSystem.Models.ComputerAsset", b =>
                {
                    b.HasBaseType("AssetTrackingSystem.Models.Asset");

                    b.HasDiscriminator().HasValue("Computer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetType = "Laptop",
                            Brand = "Dell",
                            EmployeeUsername = "anna",
                            LocalPrice = 1104m,
                            ModelName = "Latitude 5440",
                            OfficeId = 3,
                            PurchaseDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePriceUsd = 1200m,
                            SerialNumber = "DL-LAT-001",
                            WarrantyExpirationDate = new DateTime(2027, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AssetType = "Desktop Computer",
                            Brand = "HP",
                            LocalPrice = 8925m,
                            ModelName = "EliteDesk 800",
                            OfficeId = 1,
                            PurchaseDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePriceUsd = 850m,
                            SerialNumber = "HP-ED800-003",
                            WarrantyExpirationDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AssetTrackingSystem.Models.MobileAsset", b =>
                {
                    b.HasBaseType("AssetTrackingSystem.Models.Asset");

                    b.HasDiscriminator().HasValue("Mobile");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AssetType = "Mobile Phone",
                            Brand = "Apple",
                            EmployeeUsername = "michael",
                            LocalPrice = 999m,
                            ModelName = "iPhone 15",
                            OfficeId = 2,
                            PurchaseDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePriceUsd = 999m,
                            SerialNumber = "APL-IP15-002",
                            WarrantyExpirationDate = new DateTime(2028, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AssetType = "Tablet",
                            Brand = "Samsung",
                            EmployeeUsername = "ayla",
                            LocalPrice = 24000m,
                            ModelName = "Galaxy Tab S9",
                            OfficeId = 4,
                            PurchaseDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePriceUsd = 750m,
                            SerialNumber = "SMS-TABS9-004",
                            WarrantyExpirationDate = new DateTime(2027, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AssetTrackingSystem.Models.Asset", b =>
                {
                    b.HasOne("AssetTrackingSystem.Models.Office", "Office")
                        .WithMany("Assets")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("AssetTrackingSystem.Models.Office", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
